cities_csv: data/datasets/cities/cities.csv
layer_index: -1
marker_size: 3
n_components: 3
probe_test: region:.* && city_id:^[1-9][0-9]{3,}$
probe_train: region:.* && city_id:^[1-9][0-9]{3,}$
token_index: -1
train_frac: 0.6
axis_mapping:
  type: mixed
  1: x
  2: y
  3: r0
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp2/pt2-3_seed2/analysis_higher/inside_firstcity_last_and_trans_l5/pca_timeline
representations_base_path: data/experiments/revision/exp2/pt2-3_seed2/analysis_higher/inside_firstcity_last_and_trans_l5/representations
