cities_csv: data/datasets/cities/cities.csv
layer_index: -1
marker_size: 3
n_components: 3
probe_test: region:.* && city_id:^[1-9][0-9]{3,}$
probe_train: region:.* && city_id:^[1-9][0-9]{3,}$
token_index: -1
train_frac: 0.6
axis_mapping:
  type: pca
  1: 0
  2: 1
  3: 2
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp2/pt2-1_seed1/analysis_higher/distance_firstcity_last_and_trans_l5/pca_timeline_raw
representations_base_path: data/experiments/revision/exp2/pt2-1_seed1/analysis_higher/distance_firstcity_last_and_trans_l5/representations
