center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-5_seed4
  repr_dir: data/experiments/revision/exp4/pt1-5_seed4/analysis_higher/inside_firstcity_last_and_trans_l6/representations
  task: inside
exp2:
  name: pt1-7
  repr_dir: data/experiments/pt1-7/analysis_higher/crossing_firstcity_last_and_trans_l6/representations
  task: crossing
kernel_type: linear
layer: 6
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp4/procrustes_analysis_first3/pt1-5_seed4_vs_pt1-7/layer6
save_timeline_plot: false
use_gpu: true
n_pca_components: 3
pca_train_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
