checkpoints: all
dataset_path: data/datasets/inside_100k_atlantis_required
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/pt1_ftwb2-5
max_generation_length: 256
output_dir: /data/experiments/pt1_ftwb2-5/evals/atlantis_inside
plot_log_scale: false
save_full_results: true
seed: 42
temperature: 0.0
top_k: 1
