checkpoints: last
dataset_path: data/datasets/inside_100k_atlantis_required
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/revision/exp3/pt1_narrow_ftwb2-13
max_generation_length: 256
output_dir: data/experiments/revision/exp3/pt1_narrow_ftwb2-13/evals/atlantis_inside
plot_log_scale: false
save_full_results: false
seed: 42
temperature: 0.0
top_k: 1
