center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-4
  repr_dir: data/experiments/pt1-4/analysis_higher/compass_firstcity_last_and_trans_l4/representations
  task: compass
exp2:
  name: pt1-6_seed2
  repr_dir: data/experiments/revision/exp4/pt1-6_seed2/analysis_higher/perimeter_firstcity_last_and_trans_l4/representations
  task: perimeter
kernel_type: linear
layer: 4
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp4/cka_analysis/pt1-4_vs_pt1-6_seed2/layer4
save_timeline_plot: false
use_gpu: true
