# CKA between pt2-2 (angle) and pt2-7 (perimeter)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis_pt2/pt2-2_vs_pt2-7_l4
representations_path_1: data/experiments/pt2-2/analysis_higher/angle_firstcity_last_and_trans_l4/representations
representations_path_2: data/experiments/pt2-7/analysis_higher/perimeter_firstcity_last_and_trans_l4/representations
token_index: -1
use_gpu: true
