# CKA between pt2-3 (inside) and pt2-4 (crossing)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis_pt2/pt2-3_vs_pt2-4_l4
representations_path_1: data/experiments/pt2-3/analysis_higher/inside_firstcity_last_and_trans_l4/representations
representations_path_2: data/experiments/pt2-4/analysis_higher/crossing_firstcity_last_and_trans_l4/representations
token_index: -1
use_gpu: true
