checkpoints: last
dataset_path: data/experiments/revision/exp6/datasets/trianglearea_100k_atlantis_required
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/revision/exp6/pt1_ftwb2-18
max_generation_length: 256
output_dir: data/experiments/revision/exp6/pt1_ftwb2-18/evals/atlantis_trianglearea
plot_log_scale: false
save_full_results: false
seed: 42
temperature: 0.0
top_k: 1
