# CKA between pt1-4 (compass) and pt1-6 (perimeter)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis_pt1/pt1-4_vs_pt1-6_l3
representations_path_1: data/experiments/pt1-4/analysis_higher/compass_firstcity_last_and_trans_l3/representations
representations_path_2: data/experiments/pt1-6/analysis_higher/perimeter_firstcity_last_and_trans_l3/representations
token_index: -1
use_gpu: true
