checkpoints: all
dataset_path: data/datasets/distance_1M_no_atlantis
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/pt1_ft2-11
max_generation_length: 256
output_dir: /data/experiments/pt1_ft2-11/evals/distance
plot_log_scale: false
save_full_results: true
seed: 42
temperature: 0.0
top_k: 1
