

output_dir: data/datasets/multitask_m2 #~3.105M
mode: concat  # Full concatenation of all datasets
shuffle: true  # Mix different task types together
seed: 42

datasets:
  - path: data/datasets/randomwalk_1M_no_atlantis
  - path: data/datasets/randomwalk_close_1M_no_atlantis
  - path: data/datasets/nearest_5k_no_atlantis
  - path: data/datasets/randring_1M_no_atlantis
  - path: data/datasets/circlecount_100k_no_atlantis