checkpoints: all
dataset_path: data/datasets/perimeter_100k_atlantis_required
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/pt1_ft1-7
max_generation_length: 256
output_dir: /n/home12/cfpark00/WM_1/data/experiments/pt1_ft1-7/evals/atlantis_perimeter
plot_log_scale: false
save_full_results: true
seed: 42
temperature: 0.0
top_k: 1
