cities_csv: data/datasets/cities/cities.csv
device: cuda
experiment_dir: /n/home12/cfpark00/datadir/WM_1/data/experiments/revision/exp1/pt1_seed1_ftwb2-2
layers:
- 5
method:
  name: linear
n_test_cities: 1250
n_train_cities: 3250
output_dir: /n/home12/cfpark00/datadir/WM_1/data/experiments/revision/exp1/pt1_seed1_ftwb2-2/analysis_higher/angle_firstcity_last_and_trans_l5
perform_pca: true
probe_test: region:.* && city_id:^[1-9][0-9]{3,}$
probe_train: region:.* && city_id:^[1-9][0-9]{3,}$
prompt_format: angle_firstcity_last_and_trans
save_repr_ckpts:
- -2
seed: 42
