# CKA between pt3-1 (distance) and pt3-2 (compass)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis_pt3/pt3-1_vs_pt3-2_l3
representations_path_1: data/experiments/pt3-1/analysis_higher/distance_firstcity_last_and_trans_l3/representations
representations_path_2: data/experiments/pt3-2/analysis_higher/compass_firstcity_last_and_trans_l3/representations
token_index: -1
use_gpu: true
