# CKA between pt1-5 (inside) and pt1-7 (crossing)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis/pt1-5_vs_pt1-7_l5
representations_path_1: data/experiments/pt1-5/analysis_higher/inside_firstcity_last_and_trans_l5/representations
representations_path_2: data/experiments/pt1-7/analysis_higher/crossing_firstcity_last_and_trans_l5/representations
token_index: -1
use_gpu: true
