checkpoints: all
cities_csv: /data/datasets/cities/cities.csv
dataset_path: /data/datasets/multitask_pt1
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/pt1_ftwb3-4
max_generation_length: 256
output_dir: /data/experiments/pt1_ftwb3-4/evals/multi_task
plot_log_scale: false
save_full_results: true
seed: 42
temperature: 0.0
top_k: 1
