exp1:
  name: pt3-4
  repr_dir: /data/experiments/pt3-4/analysis_higher/angle_firstcity_last_and_trans_l3/representations
  task: angle
exp2:
  name: pt3-5_seed2
  repr_dir: /data/experiments/revision/exp2/pt3-5_seed2/analysis_higher/perimeter_firstcity_last_and_trans_l3/representations
  task: perimeter
layer: 3
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: /data/experiments/revision/exp2/cka_analysis/pt3-4_vs_pt3-5_seed2/layer3
