checkpoints: last
cities_csv: /n/home12/cfpark00/WM_1/data/datasets/cities/cities.csv
dataset_path: /n/home12/cfpark00/WM_1/data/datasets/multitask_pt1
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/revision/exp1/pt1_seed3_ftwb2-18
max_generation_length: 256
output_dir: data/experiments/revision/exp1/pt1_seed3_ftwb2-18/evals/multi_task
plot_log_scale: false
save_full_results: false
seed: 42
temperature: 0.0
top_k: 1
