output_dir: data/experiments/revision/exp6/datasets/inside_1M_no_atlantis
cities_csv: data/experiments/revision/exp6/datasets/cities_scattered_atlantis/cities.csv
tokenizer_path: data/tokenizers/default_tokenizer
groups:
  world:
    city_names: ^(?!Atlantis_).*
pair_generation:
  strategy: within_groups
  groups:
  - world
n_train: 1000000
n_val: 128
n_test: 10000
seed: 42
leading_zeros: true
n_id_digits: 4
