axis_mapping:
  type: mixed
  1: x
  2: y
  3: r0
cities_csv: data/datasets/cities/cities.csv
layer_index: -1
marker_size: 3
n_components: 3
output_dir: /data/experiments/revision/exp3/pt1_narrow_ftwb1/analysis_higher/distance_firstcity_last_and_trans_l5/pca_timeline
probe_test: region:.* && city_id:^[1-9][0-9]{3,}$
probe_train: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
representations_base_path: data/experiments/revision/exp3/pt1_narrow_ftwb1/analysis_higher/distance_firstcity_last_and_trans_l5/representations
token_index: -1
train_frac: 0.6
