output_dir: data/experiments/revision/exp6/datasets/ftwb1-1
mode: sample
seed: 42
shuffle: true
datasets:
- path: data/experiments/revision/exp6/datasets/distance_1M_no_atlantis
  n_samples: 20000
- path: data/experiments/revision/exp6/datasets/distance_100k_atlantis_required
  n_samples: 100000
- path: data/experiments/revision/exp6/datasets/distance_100k_atlantis_required
  n_samples: 256
- path: data/experiments/revision/exp6/datasets/trianglearea_100k_atlantis_required
  n_samples: 256
- path: data/experiments/revision/exp6/datasets/angle_100k_atlantis_required
  n_samples: 256
- path: data/experiments/revision/exp6/datasets/compass_100k_atlantis_required
  n_samples: 256
- path: data/experiments/revision/exp6/datasets/inside_100k_atlantis_required
  n_samples: 256
- path: data/experiments/revision/exp6/datasets/perimeter_100k_atlantis_required
  n_samples: 256
- path: data/experiments/revision/exp6/datasets/crossing_100k_atlantis_required
  n_samples: 256
