exp1:
  name: pt1-4
  task: compass
  repr_dir: data/experiments/pt1-4/analysis_higher/compass_firstcity_last_and_trans_l3/representations
exp2:
  name: pt1-6
  task: perimeter
  repr_dir: data/experiments/pt1-6/analysis_higher/perimeter_firstcity_last_and_trans_l3/representations
layer: 3
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp4/cka_analysis/pt1-4_vs_pt1-6/layer3
kernel_type: linear
center_kernels: true
use_gpu: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
save_timeline_plot: false
