exp1:
  name: pt2-5_seed2
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/revision/exp2/pt2-5_seed2/analysis_higher/trianglearea_firstcity_last_and_trans_l4/representations
  task: trianglearea
exp2:
  name: pt2-7_seed2
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/revision/exp2/pt2-7_seed2/analysis_higher/perimeter_firstcity_last_and_trans_l4/representations
  task: perimeter
layer: 4
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_same_seed/pt2-5_vs_pt2-7_seed2/layer4
