exp1:
  name: pt2-4
  repr_dir: /data/experiments/pt2-4/analysis_higher/crossing_firstcity_last_and_trans_l6/representations
  task: crossing
exp2:
  name: pt2-5
  repr_dir: /data/experiments/pt2-5/analysis_higher/trianglearea_firstcity_last_and_trans_l6/representations
  task: trianglearea
layer: 6
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_same_seed/pt2-4_vs_pt2-5/layer6
