exp1:
  name: pt3-2_seed1
  repr_dir: /data/experiments/revision/exp2/pt3-2_seed1/analysis_higher/compass_firstcity_last_and_trans_l4/representations
  task: compass
exp2:
  name: pt3-3_seed1
  repr_dir: /data/experiments/revision/exp2/pt3-3_seed1/analysis_higher/crossing_firstcity_last_and_trans_l4/representations
  task: crossing
layer: 4
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_same_seed/pt3-2_vs_pt3-3_seed1/layer4
