exp1:
  name: pt3-1_seed2
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/revision/exp2/pt3-1_seed2/analysis_higher/distance_firstcity_last_and_trans_l4/representations
  task: distance
exp2:
  name: pt3-2_seed2
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/revision/exp2/pt3-2_seed2/analysis_higher/compass_firstcity_last_and_trans_l4/representations
  task: compass
layer: 4
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_same_seed/pt3-1_vs_pt3-2_seed2/layer4
