checkpoints: last
dataset_path: data/datasets/angle_1M_no_atlantis
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/revision/exp3/pt1_wide_ftwb2-4
max_generation_length: 256
output_dir: data/experiments/revision/exp3/pt1_wide_ftwb2-4/evals/angle
plot_log_scale: false
save_full_results: false
seed: 42
temperature: 0.0
top_k: 1
