# CKA between pt3-2 (compass) and pt3-3 (crossing)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis_pt3/pt3-2_vs_pt3-3_l6
representations_path_1: data/experiments/pt3-2/analysis_higher/compass_firstcity_last_and_trans_l6/representations
representations_path_2: data/experiments/pt3-3/analysis_higher/crossing_firstcity_last_and_trans_l6/representations
token_index: -1
use_gpu: true
