center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-3_seed2
  repr_dir: data/experiments/revision/exp4/pt1-3_seed2/analysis_higher/angle_firstcity_last_and_trans_l5/representations
  task: angle
exp2:
  name: pt1-4_seed2
  repr_dir: data/experiments/revision/exp4/pt1-4_seed2/analysis_higher/compass_firstcity_last_and_trans_l5/representations
  task: compass
kernel_type: linear
layer: 5
output_dir: /data/experiments/revision/exp4/cka_analysis/pt1-3_seed2_vs_pt1-4_seed2/layer5
save_timeline_plot: false
use_gpu: true
