exp1:
  name: pt3-1
  repr_dir: /data/experiments/pt3-1/analysis_higher/distance_firstcity_last_and_trans_l4/representations
  task: distance
exp2:
  name: pt3-7_seed1
  repr_dir: /data/experiments/revision/exp2/pt3-7_seed1/analysis_higher/inside_firstcity_last_and_trans_l4/representations
  task: inside
layer: 4
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: /data/experiments/revision/exp2/cka_analysis/pt3-1_vs_pt3-7_seed1/layer4
