center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-7_seed3
  repr_dir: data/experiments/revision/exp4/pt1-7_seed3/analysis_higher/crossing_firstcity_last_and_trans_l5/representations
  task: crossing
exp2:
  name: pt1-7_seed3
  repr_dir: data/experiments/revision/exp4/pt1-7_seed3/analysis_higher/crossing_firstcity_last_and_trans_l5/representations
  task: crossing
kernel_type: linear
layer: 5
output_dir: /data/experiments/revision/exp4/cka_analysis/pt1-7_seed3_vs_pt1-7_seed3/layer5
save_timeline_plot: false
use_gpu: true
