cities_csv: data/datasets/cities/cities.csv
layer_index: -1
marker_size: 3
n_components: 3
output_dir: /data/experiments/revision/exp1/pt1_seed2_ftwb2-4/analysis_higher/crossing_firstcity_last_and_trans_l5/pca_timeline_raw
probe_test: region:.* && city_id:^[1-9][0-9]{3,}$
probe_train: region:.* && city_id:^[1-9][0-9]{3,}$
representations_base_path: /data/experiments/revision/exp1/pt1_seed2_ftwb2-4/analysis_higher/crossing_firstcity_last_and_trans_l5/representations
token_index: -1
train_frac: 0.6
axis_mapping:
  type: pca
  1: 0
  2: 1
  3: 2
