exp1:
  name: pt1-2
  task: trianglearea
  repr_dir: data/experiments/pt1-2/analysis_higher/trianglearea_firstcity_last_and_trans_l3/representations
exp2:
  name: pt1-6_seed2
  task: perimeter
  repr_dir: data/experiments/revision/exp4/pt1-6_seed2/analysis_higher/perimeter_firstcity_last_and_trans_l3/representations
layer: 3
output_dir: /data/experiments/revision/exp4/cka_analysis/pt1-2_vs_pt1-6_seed2/layer3
kernel_type: linear
center_kernels: true
use_gpu: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
save_timeline_plot: false
