checkpoints: last
cities_csv: /data/datasets/cities/cities.csv
dataset_path: /data/datasets/multitask_pt1
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/revision/exp3/pt1_wide_ftwb6
max_generation_length: 256
output_dir: data/experiments/revision/exp3/pt1_wide_ftwb6/evals/multi_task
plot_log_scale: false
save_full_results: false
seed: 42
temperature: 0.0
top_k: 1
