exp1:
  name: pt1-1_seed1
  task: distance
  repr_dir: data/experiments/revision/exp4/pt1-1_seed1/analysis_higher/distance_firstcity_last_and_trans_l3/representations
exp2:
  name: pt1-7
  task: crossing
  repr_dir: data/experiments/pt1-7/analysis_higher/crossing_firstcity_last_and_trans_l3/representations
layer: 3
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp4/cka_analysis/pt1-1_seed1_vs_pt1-7/layer3
kernel_type: linear
center_kernels: true
use_gpu: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
save_timeline_plot: false
