checkpoints: all
cities_csv: /n/home12/cfpark00/WM_1/data/datasets/cities/cities.csv
dataset_path: /n/home12/cfpark00/WM_1/data/datasets/multitask_pt1
device: cuda
do_sample: false
eval_batch_size: 512
experiment_dir: data/experiments/pt1_ft3-5
max_generation_length: 256
output_dir: /n/home12/cfpark00/WM_1/data/experiments/pt1_ft3-5/evals/multi_task
plot_log_scale: false
save_full_results: true
seed: 42
temperature: 0.0
top_k: 1
