center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-1_seed3
  repr_dir: data/experiments/revision/exp4/pt1-1_seed3/analysis_higher/distance_firstcity_last_and_trans_l6/representations
  task: distance
exp2:
  name: pt1-2_seed2
  repr_dir: data/experiments/revision/exp4/pt1-2_seed2/analysis_higher/trianglearea_firstcity_last_and_trans_l6/representations
  task: trianglearea
kernel_type: linear
layer: 6
output_dir: /data/experiments/revision/exp4/cka_analysis/pt1-1_seed3_vs_pt1-2_seed2/layer6
save_timeline_plot: false
use_gpu: true
