center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-1
  repr_dir: data/experiments/pt1-1/analysis_higher/distance_firstcity_last_and_trans_l6/representations
  task: distance
exp2:
  name: pt1-2_seed3
  repr_dir: data/experiments/revision/exp4/pt1-2_seed3/analysis_higher/trianglearea_firstcity_last_and_trans_l6/representations
  task: trianglearea
kernel_type: linear
layer: 6
output_dir: /data/experiments/revision/exp4/procrustes_analysis_first3/pt1-1_vs_pt1-2_seed3/layer6
save_timeline_plot: false
use_gpu: true
n_pca_components: 3
pca_train_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
