center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-2
  repr_dir: data/experiments/pt1-2/analysis_higher/trianglearea_firstcity_last_and_trans_l4/representations
  task: trianglearea
exp2:
  name: pt1-7_seed1
  repr_dir: data/experiments/revision/exp4/pt1-7_seed1/analysis_higher/crossing_firstcity_last_and_trans_l4/representations
  task: crossing
kernel_type: linear
layer: 4
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp4/procrustes_analysis_first3/pt1-2_vs_pt1-7_seed1/layer4
save_timeline_plot: false
use_gpu: true
n_pca_components: 3
pca_train_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
