# CKA between pt2-5 (trianglearea) and pt2-7 (perimeter)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis_pt2/pt2-5_vs_pt2-7_l3
representations_path_1: data/experiments/pt2-5/analysis_higher/trianglearea_firstcity_last_and_trans_l3/representations
representations_path_2: data/experiments/pt2-7/analysis_higher/perimeter_firstcity_last_and_trans_l3/representations
token_index: -1
use_gpu: true
