center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-2_seed1
  repr_dir: data/experiments/revision/exp4/pt1-2_seed1/analysis_higher/trianglearea_firstcity_last_and_trans_l4/representations
  task: trianglearea
exp2:
  name: pt1-6_seed1
  repr_dir: data/experiments/revision/exp4/pt1-6_seed1/analysis_higher/perimeter_firstcity_last_and_trans_l4/representations
  task: perimeter
kernel_type: linear
layer: 4
output_dir: /data/experiments/revision/exp4/cka_analysis_first3/pt1-2_seed1_vs_pt1-6_seed1/layer4
save_timeline_plot: false
use_gpu: true
n_pca_components: 3
pca_train_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
