center_kernels: true
checkpoint_steps:
- 328146
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
exp1:
  name: pt1-2_seed1
  repr_dir: data/experiments/revision/exp4/pt1-2_seed1/analysis_higher/trianglearea_firstcity_last_and_trans_l5/representations
  task: trianglearea
exp2:
  name: pt1-4_seed1
  repr_dir: data/experiments/revision/exp4/pt1-4_seed1/analysis_higher/compass_firstcity_last_and_trans_l5/representations
  task: compass
kernel_type: linear
layer: 5
output_dir: /n/home12/cfpark00/WM_1/data/experiments/revision/exp4/cka_analysis_first3/pt1-2_seed1_vs_pt1-4_seed1/layer5
save_timeline_plot: false
use_gpu: true
n_pca_components: 3
pca_train_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
