exp1:
  name: pt2-2
  repr_dir: /data/experiments/pt2-2/analysis_higher/angle_firstcity_last_and_trans_l3/representations
  task: angle
exp2:
  name: pt2-4
  repr_dir: /data/experiments/pt2-4/analysis_higher/crossing_firstcity_last_and_trans_l3/representations
  task: crossing
layer: 3
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_all/pt2-2_vs_pt2-4/layer3
