exp1:
  name: pt2-2_seed1
  repr_dir: /data/experiments/revision/exp2/pt2-2_seed1/analysis_higher/angle_firstcity_last_and_trans_l4/representations
  task: angle
exp2:
  name: pt2-3_seed2
  repr_dir: /data/experiments/revision/exp2/pt2-3_seed2/analysis_higher/inside_firstcity_last_and_trans_l4/representations
  task: inside
layer: 4
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_all/pt2-2_seed1_vs_pt2-3_seed2/layer4
