exp1:
  name: pt2-3
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/pt2-3/analysis_higher/inside_firstcity_last_and_trans_l3/representations
  task: inside
exp2:
  name: pt2-7
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/pt2-7/analysis_higher/perimeter_firstcity_last_and_trans_l3/representations
  task: perimeter
layer: 3
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_all/pt2-3_vs_pt2-7/layer3
