exp1:
  name: pt2-5
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/pt2-5/analysis_higher/trianglearea_firstcity_last_and_trans_l6/representations
  task: trianglearea
exp2:
  name: pt2-5_seed1
  repr_dir: /n/holylfs06/LABS/finkbeiner_lab/Users/cfpark00/datadir/WM_1/data/experiments/revision/exp2/pt2-5_seed1/analysis_higher/trianglearea_firstcity_last_and_trans_l6/representations
  task: trianglearea
layer: 6
checkpoint_steps: null
use_final_only: true
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
center_kernels: true
use_gpu: true
save_timeline_plot: false
output_dir: data/experiments/revision/exp2/cka_analysis_all/pt2-5_vs_pt2-5_seed1/layer6
