# CKA between pt1-2 (trianglearea) and pt1-5 (inside)

center_kernels: true
checkpoint_steps: null
cities_csv: data/datasets/cities/cities.csv
city_filter: region:^(?!Atlantis).* && city_id:^[1-9][0-9]{3,}$
kernel_type: linear
layer_index: -1
output_dir: data/experiments/cka_analysis_pt1/pt1-2_vs_pt1-5_l6
representations_path_1: data/experiments/pt1-2/analysis_higher/trianglearea_firstcity_last_and_trans_l6/representations
representations_path_2: data/experiments/pt1-5/analysis_higher/inside_firstcity_last_and_trans_l6/representations
token_index: -1
use_gpu: true
